# Generated by Django 4.1.3 on 2022-12-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='Halifax', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='province',
            field=models.CharField(default='NS', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=1024),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
