# Generated by Django 4.1.3 on 2023-01-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userprofile_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='iamhandsome@gmail.com', max_length=50),
        ),
    ]
