# Generated by Django 4.1.3 on 2023-05-17 18:46

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_product_id_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=account.models.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
